version: '3.8'
services:
  postgres:
    container_name: wwe
    image: postgres:latest
    restart: always
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: